import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

export async function testDynamicNotifications(db, { admin, alice, bob, otherAdmin }) {
  const migration = readFileSync(new URL('../notifications_dynamic.sql', import.meta.url), 'utf8');
  await db.exec(migration);
  await db.exec(migration);
  const aid = '10000000-0000-0000-0000-000000000099';
  const hid = '20000000-0000-0000-0000-000000000099';
  const clear = () => db.exec('delete from notificaciones_app');
  const rows = async () => (await db.query('select * from notificaciones_app')).rows;
  await clear();
  await db.exec(`select set_config('test.uid','${admin}',false);
    begin;
    insert into asignaciones(id,titulo,tipo_flujo,estado,nivel_prioridad)
      values('${aid}','Concierto','campo','pendiente','baja');
    insert into asignacion_equipo values('${aid}','${alice}');
    insert into hitos_itinerario(id,asignacion_id,orden,descripcion,completado,fecha_programada)
      values('${hid}','${aid}',1,'Llegada al almacén',false,now() + interval '10 minutes');
    commit;`);
  let notices = await rows();
  assert.equal(notices.find(n => n.perfil_id === alice).mensaje, 'Se te ha asignado al montaje: Concierto');
  assert.ok(!notices.some(n => n.perfil_id === bob));
  await clear();
  await db.exec(`update asignaciones set nivel_prioridad = 'alta' where id = '${aid}';`);
  notices = await rows();
  assert.equal(notices.filter(n => n.tipo === 'asignacion_urgente').length, 2);
  assert.ok(notices.filter(n => n.tipo === 'asignacion_urgente').every(n => n.titulo === '¡URGENTE!'));
  await clear();
  await db.exec(`update asignaciones set instrucciones = 'Revisión' where id = '${aid}';`);
  assert.ok((await rows()).every(n => n.tipo === 'asignacion_actualizada'));
  assert.equal((await rows()).find(n => n.perfil_id === alice).mensaje, 'La asignación Concierto ha sido modificada');
  await clear();
  await db.exec(`select set_config('test.uid','',false); select generate_notification_reminders(); select generate_notification_reminders();`);
  notices = await rows();
  assert.equal(notices.filter(n => n.destino_id === aid).length, 2);
  assert.ok(notices.every(n => n.perfil_id === alice));
  assert.ok(notices.some(n => n.mensaje === 'El hito Llegada al almacén está por vencer pronto'));
  assert.ok(notices.some(n => n.mensaje === 'La asignación Concierto está próxima a su fecha límite'));
  await clear();
  await db.exec(`select set_config('test.uid','${alice}',false);
    select employee_complete_milestone('${hid}','Listo');`);
  notices = await rows();
  assert.equal(notices.filter(n => n.tipo === 'hito_completado').length, 2);
  assert.ok(notices.every(n => [admin,otherAdmin].includes(n.perfil_id)));
  assert.ok(notices.filter(n => n.tipo === 'hito_completado').every(n => n.mensaje === 'Alice confirmó Llegada al almacén'));
  assert.equal(notices.filter(n => n.tipo === 'asignacion_completada').length, 2);
  assert.ok(notices.filter(n => n.tipo === 'asignacion_completada').every(n => n.mensaje === 'Alice ha completado la asignación Concierto'));
  await clear();
  await db.exec(`update asignaciones set estado = 'completada' where id = '${aid}';`);
  assert.ok((await rows()).every(n => n.mensaje === 'Alice ha completado la asignación Concierto'));
  assert.equal((await rows()).length, 0);
  await clear();
  await db.exec(`select set_config('test.uid','${admin}',false);
    begin;
    delete from asignacion_equipo where asignacion_id = '${aid}';
    insert into asignacion_equipo values('${aid}','${bob}');
    commit;`);
  assert.equal((await rows()).find(n => n.perfil_id === alice).mensaje, 'Has sido removido de la asignación Concierto');
  await clear();
  await db.exec(`select admin_delete_assignment('${aid}');`);
  assert.equal((await rows()).find(n => n.perfil_id === bob).mensaje, 'La asignación Concierto ha sido eliminada');
  await clear();
  const cid = '40000000-0000-0000-0000-000000000099';
  await db.exec(`insert into comunicados(id,asunto,mensaje) values('${cid}','Semana de eventos','Contenido privado');`);
  assert.ok((await rows()).every(n => n.titulo === 'Nuevo Comunicado de Admin' && n.mensaje === 'Semana de eventos'));
  assert.equal((await rows()).length, 3);
  await clear();
  await db.exec(`update comunicados set mensaje = 'Revisado' where id = '${cid}';`);
  assert.ok((await rows()).every(n => n.mensaje === 'El comunicado Semana de eventos ha sido modificado'));
  await clear();
  await db.exec(`delete from comunicados where id = '${cid}';`);
  assert.ok((await rows()).every(n => n.mensaje === 'El comunicado Semana de eventos ya no está disponible'));
  const jobs = (await db.query('select * from claim_notification_pushes_v2()')).rows;
  assert.ok(jobs.length > 0);
  assert.ok(jobs.every(j => j.title === 'Comunicado retirado' && j.body.includes('Semana de eventos')));
  await clear();
  await db.exec(`select set_config('test.uid','50000000-0000-0000-0000-000000000099',false);
    insert into perfiles values('50000000-0000-0000-0000-000000000099','Nuevo','tecnico');`);
  assert.equal((await rows()).length, 2);
  assert.ok((await rows()).every(n => n.titulo === 'Nuevo registro' && !n.mensaje.includes('aprobación')));
  await db.exec(`set role authenticated;`);
  await assert.rejects(db.exec('select * from claim_notification_pushes_v2();'));
  await db.exec('reset role;');
  console.log('PASS dynamic notifications: text, recipients, urgency transitions, reminders, deletion snapshots, registration and private RPC');
}
