// Run with Node and PGLITE_PATH pointing at an installed @electric-sql/pglite module.
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_PATH);
const db = new PGlite();
const admin = '00000000-0000-0000-0000-000000000001';
const alice = '00000000-0000-0000-0000-000000000002';
const bob = '00000000-0000-0000-0000-000000000003';
const otherAdmin = '00000000-0000-0000-0000-000000000004';
const assignment = '10000000-0000-0000-0000-000000000001';
const milestone = '20000000-0000-0000-0000-000000000001';
await db.exec(`
  create role anon; create role authenticated; create role service_role;
  create schema auth;
  create function auth.uid() returns uuid language sql as
    $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
  create function auth.role() returns text language sql as $$ select 'authenticated'::text $$;
  create table perfiles(id uuid primary key,nombre_completo text,rol text);
  create table asignaciones(id uuid primary key,titulo text,tipo_flujo text,ubicacion text,
    nivel_prioridad text,instrucciones text,estado text,fecha_creacion timestamptz,fecha_limite timestamptz);
  create table asignacion_equipo(asignacion_id uuid references asignaciones(id),perfil_id uuid references perfiles(id));
  create table hitos_itinerario(id uuid primary key,asignacion_id uuid references asignaciones(id),
    orden int,descripcion text,hora_estimada time,fecha_programada timestamptz,estado_hito text,
    completado bool,notas_incidencias text,hora_real_completado timestamptz);
  create table checklist_equipos(id uuid primary key,asignacion_id uuid references asignaciones(id));
  create table comunicados(id uuid primary key,asunto text,mensaje text,fecha_publicacion timestamptz,leido_por uuid[]);
  create table notificaciones_app(id uuid primary key,perfil_id uuid references perfiles(id),titulo text,mensaje text,
    leida bool,fecha_creacion timestamptz,asignacion_relacionada_id uuid references asignaciones(id));
  grant usage on schema public, auth to authenticated, anon, service_role;
  insert into perfiles values
    ('${admin}','Admin','admin'),('${alice}','Alice','tecnico'),
    ('${bob}','Bob','tecnico'),('${otherAdmin}','Supervisor','admin');
  select set_config('test.uid','${admin}',false);
`);
for (const path of ['../admin_creation_setup.sql','../assignment_checklist_setup.sql','../admin_crud_completion.sql','../notifications_setup.sql']) {
  await db.exec(readFileSync(new URL(path, import.meta.url),'utf8'));
}
// Migration must also be safe to reapply.
await db.exec(readFileSync(new URL('../notifications_setup.sql', import.meta.url),'utf8'));
const rows = async () => (await db.query('select perfil_id,tipo,leida from notificaciones_app order by perfil_id')).rows;
const clear = () => db.exec('delete from notificaciones_app');
await db.exec(`begin;
  insert into asignaciones(id,titulo,tipo_flujo,estado) values('${assignment}','Evento','campo','pendiente');
  insert into asignacion_equipo values('${assignment}','${alice}');
  insert into hitos_itinerario(id,asignacion_id,orden,descripcion,completado) values('${milestone}','${assignment}',1,'Montaje',false);
commit;`);
assert.deepEqual((await rows()).map(r => r.perfil_id), [alice,otherAdmin]);
assert.equal((await rows())[0].tipo,'asignacion_nueva');
console.log('PASS creation: only assigned employee and other administrator');
await clear();
await db.exec(`begin;
  update asignaciones set titulo = 'Evento actualizado' where id = '${assignment}';
  delete from asignacion_equipo where asignacion_id = '${assignment}';
  insert into asignacion_equipo values('${assignment}','${alice}');
commit;`);
assert.deepEqual((await rows()).map(r => r.tipo), ['asignacion_actualizada','asignacion_actualizada']);
console.log('PASS edit: one notification, no false removal/reassignment');
await clear();
await db.exec(`begin;
  delete from asignacion_equipo where asignacion_id = '${assignment}';
  insert into asignacion_equipo values('${assignment}','${bob}');
commit;`);
assert.deepEqual((await rows()).map(r => r.tipo), ['asignacion_retirada','asignacion_nueva','asignacion_actualizada']);
console.log('PASS reassignment: old and new recipients receive distinct events');
await clear();
await db.exec(`select set_config('test.uid','${bob}',false);
  select employee_complete_milestone('${milestone}', 'Listo');`);
assert.deepEqual((await rows()).map(r => r.perfil_id), [admin,otherAdmin]);
assert.ok((await rows()).every(r => r.tipo === 'estado_actualizado'));
console.log('PASS checklist: administrators informed, unrelated employee excluded');
await clear();
await db.exec(`select set_config('test.uid','${admin}',false);
  select admin_delete_assignment('${assignment}');`);
assert.deepEqual((await rows()).map(r => r.perfil_id), [bob,otherAdmin]);
assert.ok((await rows()).every(r => r.tipo === 'asignacion_eliminada'));
console.log('PASS deletion: notices survive removal of team and assignment');
await clear();
await db.exec(`insert into comunicados values(gen_random_uuid(),'Aviso','Texto',now(),'{}');`);
assert.deepEqual((await rows()).map(r => r.perfil_id), [alice,bob,otherAdmin]);
console.log('PASS bulletin: broadcast to everyone except author');
await db.exec(`select set_config('test.uid','${alice}',false); set role authenticated;`);
assert.equal((await rows()).length,1);
await db.exec('select notifications_mark_read(null);');
assert.equal((await rows())[0].leida,true);
await assert.rejects(db.exec("insert into notificaciones_app(id,perfil_id) values(gen_random_uuid(),auth.uid());"));
await assert.rejects(db.exec('select * from notification_private.devices;'));
await assert.rejects(db.exec('select * from claim_notification_pushes();'));
await db.exec('reset role;');
assert.equal((await rows()).filter(r => r.leida).length,1);
console.log('PASS permissions: own inbox/read flag only; no forged notifications or token access');
await clear();
await db.exec(`select set_config('test.uid','${admin}',false);
  update comunicados set mensaje = 'Texto revisado';`);
assert.ok((await rows()).every(r => r.tipo === 'comunicado_actualizado'));
assert.equal((await rows()).length,3);
await clear();
await db.exec('update comunicados set leido_por = array[]::uuid[];');
assert.equal((await rows()).length,0);
await db.exec('delete from comunicados;');
assert.equal((await rows()).length,3);
assert.ok((await rows()).every(r => r.tipo === 'comunicado_eliminado'));
console.log('PASS bulletin edits/deletions broadcast; read flags do not generate events');
await clear();
await db.exec(readFileSync(new URL('../notification_reminders.sql',import.meta.url),'utf8'));
await db.exec(`begin;
  insert into asignaciones(id,titulo,tipo_flujo,estado,fecha_limite)
    values('${assignment}','Reporte','administracion','pendiente',now() + interval '10 minutes');
  insert into asignacion_equipo values('${assignment}','${alice}');
commit;`);
await clear();
await db.exec("select set_config('test.uid','',false); select generate_notification_reminders(); select generate_notification_reminders();");
assert.equal((await rows()).length,1);
assert.equal((await rows())[0].perfil_id,alice);
assert.equal((await rows())[0].tipo,'recordatorio');
console.log('PASS upcoming reminders: assigned employee only, deduplicated on repeated execution');
await db.exec(`update asignaciones set fecha_limite = now() - interval '10 minutes';`);
await clear();
await db.exec('select generate_notification_reminders();');
assert.deepEqual((await rows()).map(r => r.perfil_id),[admin,alice,otherAdmin]);
console.log('PASS overdue reminders: assigned employee and administrators');
await db.exec(`update asignaciones set estado = 'completada';`);
await clear();
await db.exec('select generate_notification_reminders();');
assert.equal((await rows()).length,0);
console.log('PASS completed assignments never generate reminders');
await db.exec(`select set_config('test.uid','${alice}',false); set role authenticated;
  select register_push_device('30000000-0000-0000-0000-000000000001',repeat('a',64),'sandbox');
  reset role;
  select set_config('test.uid','${admin}',false);
  insert into comunicados values(gen_random_uuid(),'Aviso push','Texto',now(),'{}');`);
const jobs = (await db.query('select * from claim_notification_pushes()')).rows;
assert.equal(jobs.length,1);
assert.equal(jobs[0].recipient,alice);
assert.equal((await db.query('select * from claim_notification_pushes()')).rows.length,0);
await db.query('select finish_notification_push($1,$2,false,$3,false)',[jobs[0].job_id,jobs[0].lease,'Temporary failure']);
assert.equal((await db.query('select * from claim_notification_pushes()')).rows.length,0);
await db.exec("update notification_private.outbox set next_attempt = now() - interval '1 minute';");
const retried = (await db.query('select * from claim_notification_pushes()')).rows;
assert.equal(retried.length,1);
assert.notEqual(retried[0].lease,jobs[0].lease);
await db.query('select finish_notification_push($1,$2,true,null,false)',[jobs[0].job_id,jobs[0].lease]);
assert.equal((await db.query('select sent_at from notification_private.outbox')).rows[0].sent_at,null);
await db.query('select finish_notification_push($1,$2,true,null,false)',[retried[0].job_id,retried[0].lease]);
assert.notEqual((await db.query('select sent_at from notification_private.outbox')).rows[0].sent_at,null);
console.log('PASS push queue: leases exclude duplicate claims, backoff and stale acknowledgments');
await db.exec(`select set_config('test.uid','${admin}',false);
  insert into comunicados values(gen_random_uuid(),'Otro aviso','Texto',now(),'{}');
  select set_config('test.uid','${bob}',false); set role authenticated;
  select register_push_device('30000000-0000-0000-0000-000000000001',repeat('a',64),'sandbox');
  reset role;`);
assert.equal((await db.query('select * from claim_notification_pushes()')).rows.length,0);
console.log('PASS account switch: old recipient queue cannot target newly registered owner');
await db.close();
