import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

test('Android queue migration, authorization, leases, retries and account/token rotation', async () => {
  const db = new PGlite();
  const id = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
  const token = 'token-for-android-device-123456789';
  const user = n => db.query("select set_config('test.uid',$1,false)", [id(n)]);
  const register = (installation, value = token) => db.query('select register_android_push_device($1,$2)', [id(installation), value]);
  const count = async table => (await db.query(`select count(*)::int n from android_push_private.${table}`)).rows[0].n;
  const emit = n => db.query('insert into notificaciones_app values($1,$2,$3,$4)', [id(n),id(1),'Confirmación','Ana confirmó']);
  const claim = async () => (await db.query('select * from claim_android_pushes()')).rows;
  const finish = (j, success, invalid = false, lease = j.lease) => db.query('select finish_android_push($1,$2,$3,$4,$5)',
    [j.job_id,lease,success,success ? null : 'messaging/server-unavailable',invalid]);
  try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role;
      create schema auth;
      create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
      create function auth.role() returns text language sql as $$select 'authenticated'::text$$;
      create function account_is_approved() returns boolean language sql as $$select false$$;
      create table perfiles(id uuid primary key);
      create table notificaciones_app(id uuid primary key,perfil_id uuid references perfiles(id),titulo text,mensaje text);
      grant usage on schema public,auth to anon,authenticated,service_role;
      insert into perfiles values('${id(1)}'),('${id(2)}');
    `);
    // Exercise the actual existing pre-request function without modifying other migrations.
    const access = readFileSync(new URL('../account_access_setup.sql', import.meta.url), 'utf8');
    const start = access.indexOf('create or replace function public.check_account_access()');
    await db.exec(access.slice(start, access.indexOf('$$;', start) + 3));
    const migration = readFileSync(new URL('./android_push.sql', import.meta.url), 'utf8');
    await db.exec(migration);
    await db.exec(migration);
    await user(1);
    await assert.rejects(register(11, null), /invalido/);
    await db.exec('set role anon');
    await assert.rejects(register(11), /permission denied/);
    await db.exec('set role authenticated');
    await db.query("select set_config('request.path','/rpc/register_android_push_device',false)");
    await db.exec('select check_account_access()');
    await db.query("select set_config('request.path','/rpc/admin_list_accounts',false)");
    await assert.rejects(db.exec('select check_account_access()'), /aprobado/);
    await register(11);
    await assert.rejects(db.exec('select * from android_push_private.devices'), /permission denied/);
    await assert.rejects(claim(), /permission denied/);
    await assert.rejects(finish({job_id:id(50),lease:id(51)},true), /permission denied/);
    await db.exec('reset role');
    await emit(21);
    assert.equal(await count('outbox'),1);
    await db.exec('set role service_role');
    const [j] = await claim();
    assert.equal(j.title,'Confirmación');
    assert.equal(j.token,token);
    assert.equal((await claim()).length,0);
    await finish(j,true,false,id(999));
    await db.exec('reset role');
    assert.equal((await db.query('select sent_at from android_push_private.outbox')).rows[0].sent_at,null);
    await finish(j,false);
    assert.equal((await claim()).length,0);
    await db.exec("update android_push_private.outbox set next_attempt=now()-interval '1 second'");
    const [retry] = await claim();
    assert.notEqual(retry.lease,j.lease);
    await finish(j,true);
    await finish(retry,true);
    assert.equal((await claim()).length,0);
    await finish(retry,false);
    assert.notEqual((await db.query('select sent_at from android_push_private.outbox')).rows[0].sent_at,null);
    await emit(22);
    const [old] = await claim();
    await register(11,token+'-rotated');
    await finish(old,false,true);
    assert.equal(await count('devices'),1);
    assert.equal(await count('outbox'),0);
    await register(12,token+'-rotated');
    assert.equal(await count('devices'),1);
    await emit(23);
    await user(2);
    await db.query('select unregister_android_push_device($1)',[id(12)]);
    assert.equal(await count('devices'),1);
    await register(12,token+'-rotated');
    assert.equal(await count('outbox'),0);
    await emit(24);
    assert.equal(await count('outbox'),0);
    await db.query('insert into notificaciones_app values($1,$2,$3,$4)',[id(25),id(2),'Nuevo','Mensaje']);
    const [invalid] = await claim();
    await finish(invalid,false,true);
    assert.equal(await count('devices'),0);
    assert.equal(await count('outbox'),0);
    assert.equal((await db.query('select count(*)::int n from notificaciones_app')).rows[0].n,5);
    await register(13);
    await db.query('select unregister_android_push_device($1)',[id(13)]);
    assert.equal(await count('devices'),0);
  } finally { await db.close(); }
});
